# Generated by Django 4.2.26 on 2025-11-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('manager', 'Manager'), ('admin', 'Admin'), ('general_user', 'General User')], default='general_user', max_length=20),
        ),
    ]
