# Generated by Django 4.2.27 on 2025-12-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('donor', 'Donor'), ('manager', 'Manager'), ('admin', 'Admin'), ('general_user', 'General User')], default='general_user', max_length=20),
        ),
    ]
