# Generated by Django 4.2.27 on 2026-01-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_event_eventparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
