# Generated by Django 4.2.26 on 2025-12-05 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('donor_email', models.EmailField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='projects.campaign')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Transaction',
                'verbose_name_plural': 'Donation Transactions',
                'indexes': [models.Index(fields=['status', 'timestamp'], name='donations_d_status_85e9d9_idx'), models.Index(fields=['campaign', 'status'], name='donations_d_campaig_5c4298_idx')],
            },
        ),
    ]
